import{S as c,i as m}from"./assets/vendor-5b791d57.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const l of t.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();function u(r){const s={key:"42320428-e8ed9ab9e474091db19815d3a",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0},e=`https://pixabay.com/api/?${new URLSearchParams(s).toString()}`;return fetch(e,{method:"GET",mode:"cors"}).then(t=>t.json())}const a={formEL:document.querySelector(".js-search-form"),listEL:document.querySelector(".gallery")};function p(r){const o={captions:!0,captionSelector:"img",captionType:"attr",captionsData:"alt",captionPosition:"bottom",animation:250,widthRatio:.9,scaleImageToRatio:!0},s=r.hits.map(e=>`<li class="gallery-item"><a href="${e.webformatURL}">
          <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}"></a>
          <div class="bloc-content">
          <p><b>Likes: </b>${e.likes}</p>
          <p><b>Views: </b>${e.views}</p>
          <p><b>Comments: </b>${e.comments}</p>
          <p><b>Downloads: </b>${e.downloads}</p>
          </div>
          </li>`).join("");a.listEL.insertAdjacentHTML("afterbegin",s),new c(".gallery a",o).refresh(),a.formEL.reset()}const i={formEL:document.querySelector(".js-search-form"),loaderEl:document.querySelector(".loader"),galleryList:document.querySelector(".gallery")};i.loaderEl.style.display="none";i.formEL.addEventListener("submit",async r=>{r.preventDefault(),i.galleryList.innerHTML="";const o=r.target.elements.query.value.trim();i.loaderEl.style.display="block",u(o).then(s=>{s.hits.length?p(s):(m.show({message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"red",position:"topRight"}),i.galleryList.innerHTML="")}).finally(()=>{i.loaderEl.style.display="none"}),r.target.reset()});
//# sourceMappingURL=commonHelpers.js.map
